import esbuild from "esbuild";
import { builtinModules } from "module";

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: "/* Knowledge Intake Codex - generated by esbuild */"
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/*",
    "@lezer/*",
    ...builtinModules
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js"
});

if (prod) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
